### ISSUE TITLE
attempt to invoke interface method error

### ISSUE THREAD

**Issue by anshulklr** [edelworksgithub/SharedPreferences#11]
@edelworksgithub can you help me in solving this error which i'm getting when i tried using your code

```
var ref_key=sharedpreferences.getString("textinreferrer", successHandler, errorHandler);
```

i'm getting error:
Could not retrieve textinreferrer Attempt to invoke interface method 'boolean android.content.SharedPreferences.
contains(java.lang.string) on a null object reference

**Comment by edelworksgithub** [comment]
Hi @anshulklr,
Please check if the "textinreferrer" is initialized with
sharedpreferences.putString("textinreferrer", "Some Value", successHandler, errorHandler);

**Comment by anshulklr** [comment]
I have already saved my data in sharedpreferences using a broadcast receiver INSTALL_REFERRER intent, now I want to access the data inside my hybrid app.

Here is the link to the plugin  I am using for that purpose : 
https://github.com/8zrealestate/android-referrer-plugin/blob/master/src/com/eightz/mobile/cordova/plugin/android/referrer/Receiver.java

Using this plugin I want to save the sharedreference and using your plugin I want to retrieve the information I saved that time: 

somewhat like this 
sharedpreferences.getString("referrer", successHandler, errorHandler);

**Comment by edelworksgithub** [comment]
The problem is I don't use defaultSharedPreferences.
Try Initializing SharedPreference file with our plugin

sharedpreferences.getSharedPreferences(filename, mode, successHandler, errorHandler);
filename - SharedPrefernces File Name
mode - mode of Preference file. two accepted (MODE_APPEND, MODE_PRIVATE)

**Comment by anshulklr** [comment]
how can i get my shared preference file name?
@edelworksgithub 
will i have to initialize it in the other plugin?

**Comment by virajsonagra** [comment]
Hi bellow is my code i am getting error while getString function. trying to get the value it's give "undefine" key error. while the value is already set.

     document.addEventListener('deviceready', function () {
        sharedpreferences.getSharedPreferences("preferance", 'MODE_PRIVATE', onSuccess, onError);
        function onSuccess(result){
            alert("SUCCESS: \r\n"+result );
             var date = new Date();
            sharedpreferences.putString("lat", '23.0225050' ,successhandle,errorhandle);
            }
         console.log(sharedpreferences.getString("lat"));
        
       function successhandle(){
            alert("value created");
        }
        function errorhandle(error){
            alert("error:"+error);
        }
        
        function onError(){
            
        }
        }

**Comment by edelworksgithub** [comment]
@virajsonagra try placing the 
console.log(sharedpreferences.getString("lat"));
inside
function successhandle(){
        alert("value created");
console.log(sharedpreferences.getString("lat"));
}
I too had that issue ;) (I am not a tech geek)

Reason:
sharedpreferences.putString("lat", '23.0225050' ,successhandle,errorhandle);
triggers a callback either to successhandle or errorhandle which may take some time and before it happens your next line of code (as below) is executed.

console.log(sharedpreferences.getString("lat"));

Please check it and let me know.
Last but not least, thanks for using my plugin.

**Comment by MarkVlamPersie** [comment]
Hello, 
i am trying to use this plugin to set SharedPreferences in the JavaScript and retrieve it in Java. Is this even possible?

My JavaScript looks like this:

```
<script type="text/javascript">
  sharedpreferences.getSharedPreferences("MyPackage.MyApp.MySharedPreferences", MODE_APPEND, succesCallback, errorCallback);
  sharedpreferences.putString("MyKey","MyString", succesCallback,errorCallback);
  
  function succesCallback(){
    alert("succes");
  }
  function errorCallback(){
    alert("error");
  }
</script>
```

Now i am trying to get `MyString` from my Java-class like this:
```
Public getPreference(){
SharedPreferences authorization = context.getSharedPreferences("MyPackage.MyApp.MySharedPreferences", MODE_APPEND);
token = authorization.getString("MyKey", "NotFound");
}
```
But it doesn't find `MyString`. Am i missing something?

**Comment by edelworksgithub** [comment]
Dear @MarkVlamPersie 
Cordova has its own instance of activity
Try this (I don't know if this will help)
Context context = cordova.getActivity();

`Public getPreference(){
Context context = cordova.getActivity();
SharedPreferences authorization = context.getSharedPreferences("MyPackage.MyApp.MySharedPreferences", MODE_APPEND);
token = authorization.getString("MyKey", "NotFound");
}`

**Comment by MarkVP10** [comment]
@edelworksgithub Firstly, many thanks for your quick reply. With some workarounds that code seems to work. But now i face another problem where the plugin itself doesn't seem to work. 
I would like to set a sharedpreference as mentioned above. But i don't quite get how to implement it. I have the JavaScript as mentioned above like this:

```
<script type="text/javascript">
  sharedpreferences.getSharedPreferences("MyPackage.MyApp.MySharedPreferences", MODE_APPEND, succesCallback, errorCallback);
  sharedpreferences.putString("MyKey","MyString", succesCallback,errorCallback);

  function succesCallback(){
    alert("succes");
  }
  function errorCallback(){
    alert("error");
  }
</script>
```

But it won't work. Apparently sharedpreferences is undefined. When i tried:
`alert(JSON.stringify(sharedpreferences));`
it alerts `{}`.

I have included the script in my .html file like this:
`<script src="../plugins/in.edelworks.sharedpreferences/www/sharedpreferences.js"></script>`

I've tested it using a phone, so it can't be that cordova isn't defined.
Am i missing an import or something like that maybe?

**Comment by edelworksgithub** [comment]
@MarkVlamPersie sorry for the late response.
I don't know how you have created the cordova project.
If you had created using cordova command line, then please check if sharedpreferences plugin is installed in your project.
I am sorry if you you had created your project in any other ways..
Any way please reply.. and I hope this answer will help you..

**Comment by edelworksgithub** [comment]
Looks like this is "fixed". Closing for now but please feel free to re-open if this is still an issue.
