### ISSUE TITLE
Android - check. iOS - ?

### ISSUE THREAD

**Issue by adityasaxena** [edelworksgithub/SharedPreferences#13]
Hi @edelworksgithub Thank you for investing your time in making this. Would you know if there are similar alternatives I could use for iOS ?

**Comment by edelworksgithub** [comment]
Hi @adityasaxena 
Thank you for your appreciation.
I created this plugin, because there were none when I was searching.
I am learning IOS just now, So sorry to say I don't know.
But I will surely look into it and revert back if I got any...

**Comment by edelworksgithub** [comment]
Looks like this is "fixed". Closing for now but please feel free to re-open if this is still an issue.
